### PR TITLE
Added polarian

### PR DESCRIPTION
**Pull request by PolarianDev**

### CODE REVIEW

**Comment by PolarianDev** [comment]
I am your friend am I not?

**Comment by lemon-sh** [comment]
Please provide a reason as to why you think this is worth including on the website.

**Comment by PolarianDev** [comment]
> Please provide a reason as to why you think this is worth including on the website.

SEO ofc, and I am your friend 😏

**Comment by lemon-sh** [comment]
are you?

**Comment by PolarianDev** [comment]
I think?

**Comment by lemon-sh** [comment]
I hope this is a joke. If it's not, you're the most narcissistic person I've ever met in my entire life.

**Pull request closed without merging**
